from pathlib import Path
import itertools


WORKFLOW = Path("workflow").resolve()
CONFIG = Path("config").resolve()
RESULTS = Path(config.get("results_dir", "/scratch/project/bug_seq_scratch/qc_bench/results_minoverlap_1000")).resolve()
RESULTS_MAIN = Path(config.get("main_results_dir", "/scratch/project/bug_seq_scratch/qc_bench/results")).resolve()
DATA = Path("/scratch/user/s4897040/biox7021/data").resolve()
FIGURES = RESULTS / "figures"
TABLES = RESULTS / "tables"
LOGS = Path("logs/rules").resolve()

RULES = WORKFLOW / "rules"
ENVS = WORKFLOW / "envs"
BENCHMARK = RESULTS / "benchmark"

configfile: CONFIG / "config.yaml"
pepfile: str(CONFIG / "pep/project_config.yaml")
pepschema: str(CONFIG / "pep/pep_schema.yaml")

SAMPLES = pep.sample_table["sample_name"]
DEPTHS = config["depth"]
MODELS = config["model"]
REPEAT = config["repeat"]

EVAL_TRIMMERS = config["trimming"] + ["untrimmed"]
EVAL_TOOLS = config["quality"] + ["unprocessed"]

KITS = pep.sample_table["sequencing_kits"]


COMBINATIONS = []
for tool in EVAL_TOOLS:
	if tool == "fastplong":
		tool = tool + "-" + "all"
		COMBINATIONS.append(tool)
	else:
		for trimmer in EVAL_TRIMMERS:
			combo = tool + "-" + trimmer
			COMBINATIONS.append(combo)

pr_files = []

contam_report_files = expand(
    RESULTS / "assess/assembly/contaminant/{combo}/{depth}x/{model}/{sample}.{combo}.contaminants.tsv",
    combo=COMBINATIONS, depth=DEPTHS, sample=SAMPLES, model=MODELS
)

target_files = expand(
    [
        RESULTS / "assess/assembly/quast/{combo}/{depth}x/{model}/{sample}.{combo}.report.tsv",
        RESULTS / "assess/assembly/contaminant/{combo}/{depth}x/{model}/{sample}.{combo}.contaminants.tsv",
        RESULTS / "assess/assembly/missed_contigs/{combo}/{depth}x/{model}/{sample}.{combo}.{depth}x.missed_contigs.csv"
    ],
    combo=COMBINATIONS, depth=DEPTHS, sample=SAMPLES, model=MODELS
)

rule all:
	input:
		target_files,
		FIGURES / "assess/assembly/metrics/combo_main_figure_assembly_sup.png",
		FIGURES / "assess/assembly/metrics/combo_main_figure_assembly_hac.png",
		FIGURES / "assess/assembly/metrics/combo_assembly_aggregate_score_perdepth_sup.png",
		FIGURES / "assess/assembly/metrics/combo_assembly_aggregate_score_perdepth_hac.png",
		TABLES / "assess/assembly/metrics/combo_quast_compiled_metrics.csv",
		TABLES / "assess/assembly/metrics/combo_assembly_missed_contigs.csv",
		TABLES / "assess/assembly/metrics/combo_contaminant_summary_count.csv",
		TABLES / "assess/assembly/metrics/combo_assembly_metrics_master.csv",
		TABLES / "assess/assembly/metrics/combo_assembly_survey_scores_perdepth.csv",
		TABLES / "assess/assembly/metrics/combo_assembly_survey_ranking_summary_perdepth.csv",
		TABLES / "assess/assembly/metrics/combo_assembly_summary_metrics_sup.csv",
		TABLES / "assess/assembly/metrics/combo_assembly_summary_metrics_hac.csv"

include: RULES / "common.smk"
include: RULES / "trim.smk"
#include: RULES / "check.smk"
include: RULES / "quality.smk"
include: RULES / "downsample.smk"
include: RULES / "call.smk"
include: RULES / "assembly.smk"
include: RULES / "assess.smk"
include: RULES / "main_figure.smk"

